name: Swift Lint & Format

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-format:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SwiftLint and SwiftFormat
        run: |
          brew install swiftlint swiftformat

      - name: Run SwiftLint
        run: |
          swiftlint lint --strict

      - name: Run SwiftFormat (Lint Mode)
        run: |
          swiftformat .
